version: '3'

services:
  fisa-bot:
    init: true
    image: airopi/tsp-bot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    env_file:
      - .env
    tty: true
    restart: always
    volumes:
      - ./data:/app/data
      - ./resources:/app/resources
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
        - action: rebuild
          path: ./requirements.txt
