name: "another-mp2i-bot"

services:
  mp2i-bot:
    container_name: mp2i-bot
    image: ghcr.io/mp2i-kleber/another-mp2i-bot:master
    user: "1000:1000"
    build:
      context: .
      dockerfile: $PWD/Dockerfile
    env_file:
      - .env
    init: true
    tty: true
    restart: no
    volumes:
      - $PWD/data:/app/data
      - $PWD/config.toml:/app/config.toml
      - $PWD/external_data:/app/external_data
      - $PWD/resources:/app/resources
