services:
  mp2i-bot:
    image: airopi/mp2i-bot:latest
    user: "1001:1001"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    env_file:
      - .env
    init: true
    tty: true
    restart: no
    volumes:
      - ./data:/app/data
      - ./resources:/app/resources
      - ./external_data:/app/external_data
      - ./config.toml:/app/config.toml

  filebrowser:
    image: hurlenko/filebrowser
    user: "1001:1001"
    volumes:
      - ./external_data:/data
      - ./filebrowser_config:/config
    # environment:
    #   - FB_BASEURL=/filebrowser
    env_file:
      - .env
    restart: always
    expose:
      - 8080
