version: '3'

services:
  mp2i-bot:
    image: airopi/mp2i-bot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    env_file:
      - .env
    tty: true
    restart: always
    volumes:
      - ./data:/app/data
      - ./resources:/app/resources
