name: "another-mp2i-bot"

services:
  mp2i-bot:
    container_name: mp2i-bot
    image: ghcr.io/mp2i-kleber/another-mp2i-bot:master
    user: "1000:1000"
    init: true
    tty: true
    restart: no
    env_file:
      - .env
    volumes:
      - ./data/:/app/data/
      - ./config.toml:/app/config.toml
      - ./external_data/:/app/external_data/
  filebrowser:
    extends:
      file: ./compose.filebrowser.yml
      service: filebrowser
    hostname: mp2i-bot-filebrowser
    networks:
      - caddy
    volumes:
      - ./external_data:/data
  webhook:
    extends:
      file: ./compose.webhook.yml
      service: webhook
    hostname: mp2i-bot-webhook
    networks:
      - caddy
  caddy:
    extends:
      file: ./compose.caddy.yml
      service: caddy
    networks:
      - caddy

networks:
  caddy:
    name: caddy
