name: "another-mp2i-bot"

include:
  - ./compose.caddy.yml
  - ./compose.filebrowser.yml
  - ./compose.webhook.yml

services:
  mp2i-bot:
    container_name: mp2i-bot
    image: ghcr.io/mp2i-kleber/another-mp2i-bot:master
    user: "1000:1000"
    init: true
    tty: true
    restart: no
    ports:
      - 5678:5678
    env_file:
      - .env
    volumes:
      - $PWD/data:/app/data
      - $PWD/config.toml:/app/config.toml
      - $PWD/external_data:/app/external_data
    develop:
      watch:
        - action: sync
          path: ${PWD}/src
          target: /app
        - action: rebuild
          path: ${PWD}/uv.lock
        - action: rebuild
          path: ${PWD}/config.toml
        - action: rebuild
          path: ${PWD}/.env
